### ISSUE TITLE
User Authentication (OAuth 2.0)

### ISSUE THREAD

**Issue by johnambery** [sweg3302-tune-town/tune-town#10]
## Description
In order to access a user's profile data, we need to use Spotify's OAuth 2.0 to verify their account and let them get their account information.

## Acceptance Criteria
- [ ] User is able to open TuneTown and see their profile picture and username on the UI.

## Tasks
- [ ] Edit the backend to authorize the user
- [ ] Edit the UI to display variables created in the backend

## Dependencies
None.

## Notes/Additional Info
Spotipy makes this process not that hard.
