### ISSUE TITLE
Logout page

### ISSUE THREAD

**Issue by vbono** [sweg3302-tune-town/tune-town#17]
* create logout page
* fix cache
## Description
Users need to be able to logout. A page/button needs to be created for this.

## Acceptance Criteria
- [x] User can navigate to a log out page
- [x] User successfully logs out

## Tasks
- [x] HTML logout page
- [x] CSS logout page
- [x] backend logic for logging out

## Dependencies
Caching issue needs to be fixed... i think it is?

## Notes/Additional Info
This is story is for functionality, it can be made prettier later

**Comment by johnambery** [comment]
I went ahead and tried this. I think everything works well... just hoping its the same story on a mac.
What I did:
- created logout html/css
- wrote in the python file the @app-route /logout and think it is correct
