### ISSUE TITLE
Song Card HTML

### ISSUE THREAD

**Issue by johnambery** [sweg3302-tune-town/tune-town#19]
## Description
Add Song Card to the profile page that will replace how the albums and songs are currently being displayed. Get a song card form open source.

## Acceptance Criteria
- [x] All previous song display is removed
- [x] Each song displayed is in its own "box" or card

## Tasks
- [x] Find a card to use from open source
- [ ] carefully replace current HTML
- [x] Use the {{ var }} to display info from the API

## Dependencies
None

## Notes/Additional Info
Good website for open source... i will add one here later
