### ISSUE TITLE
SQL Database Creation

### ISSUE THREAD

**Issue by johnambery** [sweg3302-tune-town/tune-town#20]
## Description
This story is just to get a database started. Progress on this needs to start.

## Acceptance Criteria
- [x] An empty but formatted database has been created.

## Tasks
- [x] Create and format database
- [x] Connect to app
- [x] Write SQL query that returns friends list

## Dependencies
None

## Notes/Additional Info
@amdidier is our resident expert? 😀

**Comment by johnambery** [comment]
https://python-adv-web-apps.readthedocs.io/en/latest/flask_db1.html

**Comment by johnambery** [comment]
Database, has been created, it is possible to read and write from it as well
