### ISSUE TITLE
Get and display a song from the Spotify API

### ISSUE THREAD

**Issue by johnambery** [sweg3302-tune-town/tune-town#4]
## Description
More of an experimental story, getting ready for more complicated stories concerning displaying data. Song album and title must be displayed on the profile page.

## Acceptance Criteria
- [x] Album is shown 
- [ ] Song title is shown

## Tasks
- [x] edit html/css
- [ ] write "getter" methods?

## Dependencies
none

## Notes/Additional Info
none
